name: Test and Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Environment指定を削除し、環境変数を直接使用
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      id: test
      run: npm test
      continue-on-error: true
    
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "channel": "${{ vars.SLACK_CHANNEL_ID }}",
            "text": "${{ steps.test.outcome == 'success' && '✅ テスト成功!' || '❌ テスト失敗!' }} - ${{ github.repository }} (${{ github.ref_name }})",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.test.outcome == 'success' && '✅ テスト成功!' || '❌ テスト失敗!' }} - *${{ github.repository }}* (${{ github.ref_name }})\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|詳細を確認>"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ vars.SLACK_BOT_TOKEN }}
